from typing import List

def simplify_nth_point(*args, **kwargs) -> List[float]:
    ...

def simplify_radial_distance(*args, **kwargs) -> List[float]:
    ...

def simplify_perpendicular_distance(*args, **kwargs) -> List[float]:
    ...

def simplify_reumann_witkam(*args, **kwargs) -> List[float]:
    ...

def simplify_opheim(*args, **kwargs) -> List[float]:
    ...

def simplify_lang(*args, **kwargs) -> List[float]:
    ...

def simplify_douglas_peucker(*args, **kwargs) -> List[float]:
    ...

def simplify_douglas_peucker_n(*args, **kwargs) -> List[float]:
    ...
